title:            Ricardo Gehrke Filho
tagline:          ''
description:      'Organizar, compartilhar e incrementar conhecimento sobre desenvolvimento web e mobile.'
url:              ricardofilho.com.br
baseurl:          /

markdown:         kramdown
highlighter:      rouge
