title:            Ricardo Gehrke Filho
tagline:          ''
description:      'Mussum Ipsum, cacilds vidis litro abertis. Casamentiss faiz malandris se pirulitá.'
url:              ricardofilho.com.br
baseurl:          /

markdown:         kramdown
highlighter:      rouge
