# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            iOS Dev Blog
tagline:          ''
description:      ''
url:              ricardo0100.github.io
baseurl:          /
